PoolStudio.WEB/Models/ItemTest.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace PoolStudio.WEB.Models
{
    public class ItemTest
    {
        [Key]
        public int ItemTestId { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [StringLength(100, ErrorMessage = "Límite de caracteres excedido")]
        [Display(Name = "Nombre")]
        public string ItemName { get; set; }

        [StringLength(100, ErrorMessage = "Límite de caracteres excedido")]
        [Display(Name = "Modelo")]
        public string Modelo { get; set; }

        [StringLength(100, ErrorMessage = "Límite de caracteres excedido")]
        [Display(Name = "Marca")]
        public string Brand { get; set; }

        [MaxLength(1000, ErrorMessage = "Límite de caracteres excedido.")]
        [Display(Name = "Descripción")]
        public string Comment { get; set; }
    }
}

PoolStudio.WEB/Controllers/ItemTestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PoolStudio.WEB.Data;
using PoolStudio.WEB.Models;

namespace PoolStudio.WEB.Controllers
{
    public class ItemTestsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ItemTestsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ItemTests
        public async Task<IActionResult> Index(int pg = 1)
        {
            List<ItemTest> itemTests = _context.ItemTests.ToList();

            const int pageSize = 5;
            if (pg < 1)
                pg = 1;

            int recsCount = itemTests.Count();

            var pager = new Pager(recsCount, pg, pageSize);

            int recSkip = (pg - 1) * pageSize;

            var data = itemTests.Skip(recSkip).Take(pager.PageSize).ToList();

            this.ViewBag.Pager = pager;

            return View(data);
        }

        // GET: ItemTests/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var itemTest = await _context.ItemTests
                .FirstOrDefaultAsync(m => m.ItemTestId == id);
            if (itemTest == null)
            {
                return NotFound();
            }

            return View(itemTest);
        }

        // GET: ItemTests/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ItemTests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ItemTestId,ItemName,Modelo,Brand,Comment")] ItemTest itemTest)
        {
            if (ModelState.IsValid)
            {
                _context.Add(itemTest);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(itemTest);
        }

        // GET: ItemTests/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var itemTest = await _context.ItemTests.FindAsync(id);
            if (itemTest == null)
            {
                return NotFound();
            }
            return View(itemTest);
        }

        // POST: ItemTests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ItemTestId,ItemName,Modelo,Brand,Comment")] ItemTest itemTest)
        {
            if (id != itemTest.ItemTestId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(itemTest);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemTestExists(itemTest.ItemTestId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(itemTest);
        }

        // GET: ItemTests/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var itemTest = await _context.ItemTests
                .FirstOrDefaultAsync(m => m.ItemTestId == id);
            if (itemTest == null)
            {
                return NotFound();
            }

            return View(itemTest);
        }

        // POST: ItemTests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var itemTest = await _context.ItemTests.FindAsync(id);
            _context.ItemTests.Remove(itemTest);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ItemTestExists(int id)
        {
            return _context.ItemTests.Any(e => e.ItemTestId == id);
        }
    }
}

PoolStudio.WEB/Views/ItemTests/Create.cshtml
@model PoolStudio.WEB.Models.ItemTest

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ItemTest</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ItemName" class="control-label"></label>
                <input asp-for="ItemName" class="form-control" />
                <span asp-validation-for="ItemName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comment" class="control-label"></label>
                <input asp-for="Comment" class="form-control" />
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PoolStudio.WEB/Views/ItemTests/Delete.cshtml
@model PoolStudio.WEB.Models.ItemTest

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ItemTest</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comment)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ItemTestId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PoolStudio.WEB/Views/ItemTests/Details.cshtml
@model PoolStudio.WEB.Models.ItemTest

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ItemTest</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ItemName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ItemName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Brand)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Brand)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comment)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ItemTestId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PoolStudio.WEB/Views/ItemTests/Edit.cshtml
@model PoolStudio.WEB.Models.ItemTest

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ItemTest</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ItemTestId" />
            <div class="form-group">
                <label asp-for="ItemName" class="control-label"></label>
                <input asp-for="ItemName" class="form-control" />
                <span asp-validation-for="ItemName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Brand" class="control-label"></label>
                <input asp-for="Brand" class="form-control" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comment" class="control-label"></label>
                <input asp-for="Comment" class="form-control" />
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PoolStudio.WEB/Views/ItemTests/Index.cshtml
@model IEnumerable<PoolStudio.WEB.Models.ItemTest>

@{
    ViewData["Title"] = "Index";

    Pager pager = new Pager();

    int pageNo = 0;

    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}

    <h1>
        Prueba     <a class="btn btn-primary" asp-action="Create">Agregar</a>
    </h1>

<p>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ItemName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modelo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Brand)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Comment)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ItemName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Modelo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Brand)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comment)
            </td>
            <td>
                <a class="btn btn-warning btn-sm" asp-action="Edit" asp-route-id="@item.ItemTestId">Editar</a> |
                <a class="btn btn-info btn-sm" asp-action="Details" asp-route-id="@item.ItemTestId">Detalles</a> |
                <a class="btn btn-danger btn-sm" asp-action="Delete" asp-route-id="@item.ItemTestId">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>


@* Paginación (Lo correcto es hacerlo con un partial view(que ya está creado), pero hay un bobo y mientras tanto se deja así.) *@

<div class="container">
    @if (pager.TotalPages > 0)
    {
    <ul class="pagination justify-content-end">

        @if (pager.CurrentPage > 1)
        {
            <li class="page-item">
                <a class="page-link" asp-controller="ItemTests" asp-action="Index" asp-route-pg="1">Inicio</a>
            </li>

            <li class="page-item">
                <a class="page-link" asp-controller="ItemTests" asp-action="Index" asp-route-pg="@(pager.CurrentPage - 1)">Anterior</a>
            </li>
        }

        @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
        {
            <li class="page-item @(pge == pager.CurrentPage ? "active" : "")">
                <a class="page-link" asp-controller="ItemTests" asp-action="Index" asp-route-pg="@pge">@pge</a>
            </li>
        }

        @if (pager.CurrentPage < pager.TotalPages)
        {
            <li class="page-item">
                <a class="page-link" asp-controller="ItemTests" asp-action="Index" asp-route-pg="@(pager.CurrentPage + 1)">Siguiente</a>
            </li>

            <li class="page-item">
                <a class="page-link" asp-controller="ItemTests" asp-action="Index" asp-route-pg="@(pager.TotalPages)">Final</a>
            </li>
        }

    </ul>
    }

</div>