PoolStudio.WEB/Models/Item.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace PoolStudio.WEB.Models
{
    public class Item
    {
        [Key]
        public int ItemId { get; set; }

        [Required]
        [Display(Name = "Categoría")]
        [ForeignKey("ItemType")]
        public int ClasificationId { get; set; }
        public Clasification Clasification { get; set; }

        [Required(ErrorMessage = "Este campo es obligatorio")]
        [StringLength(100, ErrorMessage = "Límite de caracteres excedido")]
        [Display(Name = "Nombre")]
        public string ItemName { get; set; }

        [StringLength(100, ErrorMessage = "Límite de caracteres excedido")]
        [Display(Name = "Modelo")]
        public string Modelo { get; set; }

        [StringLength(100, ErrorMessage = "Límite de caracteres excedido")]
        [Display(Name = "Marca")]
        public string Brand { get; set; }


        [MaxLength(1000, ErrorMessage = "Límite de caracteres excedido.")]
        [Display(Name = "Descripción")]
        public string Comment { get; set; }

    }
}

PoolStudio.WEB/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PoolStudio.WEB.Data;
using PoolStudio.WEB.Models;

namespace PoolStudio.WEB.Controllers
{
    public class ItemsController : Controller
    {
        private readonly ApplicationDbContext _context;
        [Obsolete]
        private readonly IHostingEnvironment _hostEnvironment;

        [Obsolete]
        public ItemsController(ApplicationDbContext context, IHostingEnvironment hostEnvironment)
        {
            _context = context;
            this._hostEnvironment = hostEnvironment;
        }

        public async Task<IActionResult> Category()
        {
            return View(await _context.Item.ToListAsync());
        }


        // GET: Items
        public async Task<IActionResult> Index(int pg = 1)
        {
            List<Item> items = _context.Item.Include(i => i.Clasification).ToList();

            const int pageSize = 5;
            if (pg < 1)
                pg = 1;

            int recsCount = items.Count();

            var pager = new Pager(recsCount, pg, pageSize);

            int recSkip = (pg - 1) * pageSize;

            var data = items.Skip(recSkip).Take(pager.PageSize).ToList();

            this.ViewBag.Pager = pager;

            return View(data);
        }

        [HttpGet]
        public async Task<IActionResult> Search(string varSearch)
        {
            ViewData["GetDetails"] = varSearch;

            var varQuery = from x in _context.Item.Include(o => o.Clasification) select x;
            if (!String.IsNullOrEmpty(varSearch))
            {
                varQuery = varQuery.Where(
                    x => x.Clasification.ItemType.Contains(varSearch) || 
                    x.ItemName.Contains(varSearch) || 
                    x.Modelo.Contains(varSearch) || 
                    x.Brand.Contains(varSearch) || 
                    x.Comment.Contains(varSearch)
                    );
            }

            return View(await varQuery.AsNoTracking().ToListAsync());
        }

        [HttpGet]
        public async Task<IActionResult> CategorySearch(string varCatSearch)
        {
            ViewData["GetDetails"] = varCatSearch;

            var varQuery = from x in _context.Item.Include(o => o.Clasification) select x;
            if (!String.IsNullOrEmpty(varCatSearch))
            {
                varQuery = varQuery.Where(
                    x => x.Clasification.ItemType.Contains(varCatSearch));
            }

            return View(await varQuery.AsNoTracking().ToListAsync());
        }

        // GET: Items/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Item
                .Include(i => i.Clasification)
                .FirstOrDefaultAsync(m => m.ItemId == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // GET: Items/Create
        public IActionResult Create()
        {
            ViewData["ClasificationId"] = new SelectList(_context.Clasification, "ClasificationId", "ItemType");
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Obsolete]
        public async Task<IActionResult> Create([Bind("ItemId,ImageFile,ClasificationId,ItemName,Modelo,Brand,Comment")] Item item)
        {
            if (ModelState.IsValid)
            {
                // Save image to wwwroot/UserImages
                string wwwRootPath = _hostEnvironment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(item.ImageFile.FileName);
                string extension = Path.GetExtension(item.ImageFile.FileName);
                item.ImageName = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                string path = Path.Combine(wwwRootPath + "/Imagenes/", fileName);
                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await item.ImageFile.CopyToAsync(fileStream);
                }

                // Insert record
                _context.Add(item);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClasificationId"] = new SelectList(_context.Clasification, "ClasificationId", "ItemType", item.ClasificationId);
            return View(item);
        }

        // GET: Items/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Item.FindAsync(id);
            if (item == null)
            {
                return NotFound();
            }
            ViewData["ClasificationId"] = new SelectList(_context.Clasification, "ClasificationId", "ItemType", item.ClasificationId);
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ItemId,ImageName,ClasificationId,ItemName,Modelo,Brand,Comment")] Item item)
        {
            if (id != item.ItemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(item);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemExists(item.ItemId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClasificationId"] = new SelectList(_context.Clasification, "ClasificationId", "ItemType", item.ClasificationId);
            return View(item);
        }

        // GET: Items/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Item
                .Include(i => i.Clasification)
                .FirstOrDefaultAsync(m => m.ItemId == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Obsolete]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var item = await _context.Item.FindAsync(id);

            // Delete image from wwwroot/UserImages
            var imagePath = Path.Combine(_hostEnvironment.WebRootPath, "Imagenes", item.ImageName);
            if (System.IO.File.Exists(imagePath))
                System.IO.File.Delete(imagePath);

            // Delete the record
            _context.Item.Remove(item);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ItemExists(int id)
        {
            return _context.Item.Any(e => e.ItemId == id);
        }
    }
}

PoolStudio.WEB/Views/Items/Category.cshtml
@model IEnumerable<PoolStudio.WEB.Models.Item>

    <style>

        #container{
            width: 100%;
            margin-top: 10%;
            letter-spacing: 1px;
        }

        .container h2{
            background: #0062cc;
            color: #fff;
            width: 180px;
            font-size: 24px;
            padding: 5px;
            height: 39px;
        }

        .container h2::after{
            content: '';
            border-top: 38px solid #0062cc;
            border-right: 40px solid transparent;
            position: relative;
            left: 42px;
            top: 34px;
        }

        .row{
            margin-top: 30px;
        }

        .imagen{
            width: 110%;
            height: 270px;
        }

        .product-bottom .fa{
            color: #28a745;
            font-size: 10px;
        }

        .product-bottom h3{
            font-size: 24px;
            font-weight: bold;
        }

        .overlay{
            display: block;
            opacity: 0;
            position: absolute;
            top: 10%;
            margin-left: 0;
            width: 70px;
        }

        .product-top:hover {
            border: 3px solid #0062cc;
        }

        .product-top:hover .overlay{
            opacity: 1;
            margin-left: 5%;
            transition: 0.5s;
        }

        .overlay .fa{
            cursor: pointer;
            background-color: #000;
            color: #000;
            height: 35px;
            width: 35px;
            font-size: 20px;
            padding: 7px;
            margin: 5%;
            margin-bottom: 5%;
        }

        .overlay .btn-secondary{
            background: #fff !important;
            border: none !important;
            box-shadow: none !important;
        }

    </style>

<div id="container" class="container">

    <h2 style="font-family: sans-serif;">Categorías</h2>
    <div id="row" class="row">

        <div class="col-md-3">

            <div class="product-top">

                <img title="Accesorios" class="imagen" src="~/Category_Img/Accesorios.jpg" />

                <div class="overlay">

                    <a href="https://localhost:44351/Items/CategorySearch?varCatSearch=Accesorios&CategorySearch=Buscar" title="Ir a la vista" style="background-color: #FDFEFE;" class="btn btn"><i class="far fa-eye"></i></a>

                </div>

            </div>

            <div class="product-bottom text-center">
                <hr>
                <a href="https://localhost:44351/Items/CategorySearch?varCatSearch=Accesorios&CategorySearch=Buscar"><h3 style="font-family: sans-serif; color: #000;">Accesorios</h3></a>

            </div>

        </div>

        <div class="col-md-3">

            <div class="product-top">

                <img title="Equipos" class="imagen" src="~/Category_Img/equipos.png" />

                <div class="overlay">
                    <hr>
                    <a href="https://localhost:44351/Items/CategorySearch?varCatSearch=Equipos&CategorySearch=Buscar" title="Ir a la vista" style="background-color: #FDFEFE;" class="btn btn"><i class="far fa-eye"></i></a>

                </div>

            </div>

            <div class="product-bottom text-center">
                <hr>
                <a href="https://localhost:44351/Items/CategorySearch?varCatSearch=Equipos&CategorySearch=Buscar"><h3 style="font-family: sans-serif; color: #000;">Equipos</h3></a>

            </div>

        </div>

        <div class="col-md-3">

            <div class="product-top">

                <img title="Químicos" class="imagen" src="~/Category_Img/Quimicos.jpg" />

                <div class="overlay">
                    <hr>
                    <a href="https://localhost:44351/Items/CategorySearch?varCatSearch=Quimicos&CategorySearch=Buscar" title="Ir a la vista" style="background-color: #FDFEFE;" class="btn btn"><i class="far fa-eye"></i></a>

                </div>

            </div>

            <div class="product-bottom text-center">
                <hr>
                <a href="https://localhost:44351/Items/CategorySearch?varCatSearch=Quimicos&CategorySearch=Buscar"><h3 style="font-family: sans-serif; color: #000;">Químicos</h3></a>

            </div>

        </div>

        <div class="col-md-3">

            <div class="product-top">

                <img title="Repuestos" class="imagen" src="~/Category_Img/Repuestos.jpg" />

                <div class="overlay">
                    <hr>
                    <a href="https://localhost:44351/Items/CategorySearch?varCatSearch=Repuestos&CategorySearch=Buscar" title="Ir a la vista" style="background-color: #FDFEFE;" class="btn btn"><i class="far fa-eye"></i></a>

                </div>

            </div>

            <div class="product-bottom text-center">
                <hr>
                <a href="https://localhost:44351/Items/CategorySearch?varCatSearch=Repuestos&CategorySearch=Buscar"><h3 style="font-family: sans-serif; color: #000;">Repuestos</h3></a>

            </div>

        </div>


    </div>

</div>

PoolStudio.WEB/Views/Items/CategorySearch.cshtml
@model IEnumerable<PoolStudio.WEB.Models.Item>


@{


    ViewData["Title"] = "Index";

    Pager pager = new Pager();

    int pageNo = 0;

    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }

}

<style>
    #botones {
        margin-left: 10px;
        height: 38px;
        margin-top: 220px;
    }

    #boton2 {
        margin-left: 10px;
        height: 38px;
        margin-top: 220px;
    }

    #buscador {
        width: 250px;
        margin-left: 450px;
        margin-top: 220px;
    }

    .main {
        margin: 0 auto;
        width: auto;
        padding: 6%;
    }

    .card {
        width: 100%;
        display: inline-block;
        box-shadow: 2px 2px 20px #000000;
        border-radius: 5px;
        margin: 0 auto;
    }

    .image img {
        width: 300px;
        height: 300px;
        border-top-right-radius: 5px;
        border-top-left-radius: 5px;
        border-bottom-left-radius: 5px;
        border-bottom-right-radius: 5px;
    }

    .title {
        text-align: center;
        padding: 10px;
    }

    h1 {
        font-size: 20px;
    }

    .des {
        padding: 3px;
        text-align: center;
        padding-top: 10px;
        border-bottom-right-radius: 5px;
        border-bottom-left-radius: 5px;
    }

    button {
        margin-top: 40px;
        margin-bottom: 10px;
        background-color: white;
        border: 1px solid #2E86C1;
        color: #2E86C1;
        border-radius: 5px;
        padding: 10px;
    }

        button:hover {
            background-color: #2E86C1;
            color: white;
            transition: .5s;
            cursor: pointer;
        }

    #a {
        color: #2E86C1;
    }

        #a:hover {
            color: white;
        }
</style>



<form method="get" asp-action="Search">

    <div class="row" style="margin: 0 auto; padding-right: 310px; padding-bottom: 100px; margin-left: auto; margin-right: auto;">
        <h2 style="margin-left:100px; margin-top:220px;">
            Productos
            <a class="btn btn-outline-primary" asp-action="Create">
                Añadir
            </a>
        </h2>


        <input style="margin-top:220px;" id="buscador" type="search" placeholder="Escriba aquí..." value="@ViewData["GetDetails"]" name="varCatSearch" class="form-control" />
        <input id="boton2" type="submit" name="CategorySearch" value="Buscar" class="btn btn-outline-success" />
        <a id="botones" asp-action="Index" class="btn btn-outline-dark">
            Ver todos
        </a>

        <div class="container" style=" padding-right: 250px; padding-left: 250px;"></div>
    </div>

</form>


@foreach (var item in Model)
{

    <div class="main">

        <!--cards -->

        <div class="row">

            <div class="card">

                <div class="image">


                    <img src="@("~/Imagenes/" + item.ImageName)" asp-append-version="true" />

                    <div class="title">
                        <h1>
                            @Html.DisplayFor(modelItem => item.ItemName)
                        </h1>
                    </div>
                    <div class="des">
                        <p>@Html.DisplayFor(modelItem => item.Clasification.ItemType)</p>
                        <button asp-action="Details" asp-route-id="@item.ItemId">
                            <a id="a" class="btn btn" asp-action="Details" asp-route-id="@item.ItemId">
                                Más detalles...
                            </a>
                        </button>


                    </div>

                </div>

            </div>

        </div>
        <!--cards -->
    </div>
}


@* Paginación (Lo correcto es hacerlo con un partial view(que ya está creado), pero hay un bobo y mientras tanto se deja así.) *@

<div class="container">
    @if (pager.TotalPages > 0)
    {
        <ul class="pagination justify-content-end">

            @if (pager.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="Items" asp-action="Index" asp-route-pg="1">Inicio</a>
                </li>

                <li class="page-item">
                    <a class="page-link" asp-controller="Items" asp-action="Index" asp-route-pg="@(pager.CurrentPage - 1)">Anterior</a>
                </li>
            }

            @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
            {
                <li class="page-item @(pge == pager.CurrentPage ? "active" : "")">
                    <a class="page-link" asp-controller="Items" asp-action="Index" asp-route-pg="@pge">@pge</a>
                </li>
            }

            @if (pager.CurrentPage < pager.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="Items" asp-action="Index" asp-route-pg="@(pager.CurrentPage + 1)">Siguiente</a>
                </li>

                <li class="page-item">
                    <a class="page-link" asp-controller="Items" asp-action="Index" asp-route-pg="@(pager.TotalPages)">Final</a>
                </li>
            }

        </ul>
    }

</div>

PoolStudio.WEB/Views/Items/Index.cshtml
@model IEnumerable<PoolStudio.WEB.Models.Item>


@{


    ViewData["Title"] = "Index";

    Pager pager = new Pager();

    int pageNo = 0;

    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }

}

<style>
    #botones {
        margin-left: 10px;
        height: 38px;
        margin-top: 220px;
    }

    #boton2 {
        margin-left: 10px;
        height: 38px;
        margin-top: 220px;
    }

    #buscador {
        width: 250px;
        margin-left: 450px;
        margin-top: 220px;
    }

    .main {
        margin: 0 auto;
        width: auto;
        padding: 6%;
    }

    .card {
        width: 100%;
        display: inline-block;
        box-shadow: 2px 2px 20px #000000;
        border-radius: 5px;
        margin: 0 auto;
    }

    .image img {
        width: 300px;
        height: 300px;
        border-top-right-radius: 5px;
        border-top-left-radius: 5px;
        border-bottom-left-radius: 5px;
        border-bottom-right-radius: 5px;
    }

    .title {
        text-align: center;
        padding: 10px;
    }

    h1 {
        font-size: 20px;
    }

    .des {
        padding: 3px;
        text-align: center;
        padding-top: 10px;
        border-bottom-right-radius: 5px;
        border-bottom-left-radius: 5px;
    }

    button {
        margin-top: 40px;
        margin-bottom: 10px;
        background-color: white;
        border: 1px solid #2E86C1;
        color: #2E86C1;
        border-radius: 5px;
        padding: 10px;
    }

        button:hover {
            background-color: #2E86C1;
            color: white;
            transition: .5s;
            cursor: pointer;
        }

    #a {
        color: #2E86C1;
    }

        #a:hover {
            color: white;
        }

</style>



<form method="get" asp-action="Search">

    <div class="row" style="margin: 0 auto; padding-right: 310px; padding-bottom: 100px; margin-left: auto; margin-right: auto;">
        <h2 style="margin-left:100px; margin-top:220px;">
            Productos
            <a class="btn btn-outline-primary" asp-action="Create">
                Añadir
            </a>
        </h2>


        <input style="margin-top:220px;" id="buscador" type="search" placeholder="Escriba aquí..." value="@ViewData["GetDetails"]" name="varSearch" class="form-control" />
        <input id="boton2" type="submit" name="Search" value="Buscar" class="btn btn-outline-success" />
        <a id="botones" asp-action="Index" class="btn btn-outline-dark">
            Ver todos
        </a>

        <div class="container" style=" padding-right: 250px; padding-left: 250px;"></div>
    </div>

</form>


@foreach (var item in Model)
{

    <div class="main">

        <!--cards -->

        <div class="row">

            <div class="card">

                <div class="image">


                    <img src="@("~/Imagenes/" + item.ImageName)" asp-append-version="true" />

                    <div class="title">
                        <h1>
                            @Html.DisplayFor(modelItem => item.ItemName)
                        </h1>
                    </div>
                    <div class="des">
                        <p>@Html.DisplayFor(modelItem => item.Clasification.ItemType)</p>
                        <button asp-action="Details" asp-route-id="@item.ItemId">
                            <a id="a" class="btn btn" asp-action="Details" asp-route-id="@item.ItemId">
                                Más detalles...
                            </a>
                        </button>
                        

                    </div>

                </div>

            </div>

        </div>
        <!--cards -->
    </div>
}


    @* Paginación (Lo correcto es hacerlo con un partial view(que ya está creado), pero hay un bobo y mientras tanto se deja así.) *@

    <div class="container">
        @if (pager.TotalPages > 0)
        {
            <ul class="pagination justify-content-end">

                @if (pager.CurrentPage > 1)
                {
                    <li class="page-item">
                        <a class="page-link" asp-controller="Items" asp-action="Index" asp-route-pg="1">Inicio</a>
                    </li>

                    <li class="page-item">
                        <a class="page-link" asp-controller="Items" asp-action="Index" asp-route-pg="@(pager.CurrentPage - 1)">Anterior</a>
                    </li>
                }

                @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
                {
                    <li class="page-item @(pge == pager.CurrentPage ? "active" : "")">
                        <a class="page-link" asp-controller="Items" asp-action="Index" asp-route-pg="@pge">@pge</a>
                    </li>
                }

                @if (pager.CurrentPage < pager.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link" asp-controller="Items" asp-action="Index" asp-route-pg="@(pager.CurrentPage + 1)">Siguiente</a>
                    </li>

                    <li class="page-item">
                        <a class="page-link" asp-controller="Items" asp-action="Index" asp-route-pg="@(pager.TotalPages)">Final</a>
                    </li>
                }

            </ul>
        }

    </div>

PoolStudio.WEB/Views/Items/Search.cshtml
@model IEnumerable<PoolStudio.WEB.Models.Item>


@{


    ViewData["Title"] = "Index";

    Pager pager = new Pager();

    int pageNo = 0;

    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }

}

<style>
    #botones {
        margin-left: 10px;
        height: 38px;
        margin-top: 220px;
    }

    #boton2 {
        margin-left: 10px;
        height: 38px;
        margin-top: 220px;
    }

    #buscador {
        width: 250px;
        margin-left: 450px;
        margin-top: 220px;
    }

    .main {
        margin: 0 auto;
        width: auto;
        padding: 6%;
    }

    .card {
        width: 100%;
        display: inline-block;
        box-shadow: 2px 2px 20px #000000;
        border-radius: 5px;
        margin: 0 auto;
    }

    .image img {
        width: 300px;
        height: 300px;
        border-top-right-radius: 5px;
        border-top-left-radius: 5px;
        border-bottom-left-radius: 5px;
        border-bottom-right-radius: 5px;
    }

    .title {
        text-align: center;
        padding: 10px;
    }

    h1 {
        font-size: 20px;
    }

    .des {
        padding: 3px;
        text-align: center;
        padding-top: 10px;
        border-bottom-right-radius: 5px;
        border-bottom-left-radius: 5px;
    }

    button {
        margin-top: 40px;
        margin-bottom: 10px;
        background-color: white;
        border: 1px solid #2E86C1;
        color: #2E86C1;
        border-radius: 5px;
        padding: 10px;
    }

        button:hover {
            background-color: #2E86C1;
            color: white;
            transition: .5s;
            cursor: pointer;
        }

    #a {
        color: #2E86C1;
    }

        #a:hover {
            color: white;
        }
</style>



<form method="get" asp-action="Search">

    <div class="row" style="margin: 0 auto; padding-right: 310px; padding-bottom: 100px; margin-left: auto; margin-right: auto;">
        <h2 style="margin-left:100px; margin-top:220px;">
            Productos
            <a class="btn btn-outline-primary" asp-action="Create">
                Añadir
            </a>
        </h2>


        <input style="margin-top:220px;" id="buscador" type="search" placeholder="Escriba aquí..." value="@ViewData["GetDetails"]" name="varSearch" class="form-control" />
        <input id="boton2" type="submit" name="Search" value="Buscar" class="btn btn-outline-success" />
        <a id="botones" asp-action="Index" class="btn btn-outline-dark">
            Ver todos
        </a>

        <div class="container" style=" padding-right: 250px; padding-left: 250px;"></div>
    </div>

</form>


@foreach (var item in Model)
{

    <div class="main">

        <!--cards -->

        <div class="row">

            <div class="card">

                <div class="image">


                    <img src="@("~/Imagenes/" + item.ImageName)" asp-append-version="true" />

                    <div class="title">
                        <h1>
                            @Html.DisplayFor(modelItem => item.ItemName)
                        </h1>
                    </div>
                    <div class="des">
                        <p>@Html.DisplayFor(modelItem => item.Clasification.ItemType)</p>
                        <button asp-action="Details" asp-route-id="@item.ItemId">
                            <a id="a" class="btn btn" asp-action="Details" asp-route-id="@item.ItemId">
                                Más detalles...
                            </a>
                        </button>


                    </div>

                </div>

            </div>

        </div>
        <!--cards -->
    </div>
}


@* Paginación (Lo correcto es hacerlo con un partial view(que ya está creado), pero hay un bobo y mientras tanto se deja así.) *@

<div class="container">
    @if (pager.TotalPages > 0)
    {
        <ul class="pagination justify-content-end">

            @if (pager.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="Items" asp-action="Index" asp-route-pg="1">Inicio</a>
                </li>

                <li class="page-item">
                    <a class="page-link" asp-controller="Items" asp-action="Index" asp-route-pg="@(pager.CurrentPage - 1)">Anterior</a>
                </li>
            }

            @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
            {
                <li class="page-item @(pge == pager.CurrentPage ? "active" : "")">
                    <a class="page-link" asp-controller="Items" asp-action="Index" asp-route-pg="@pge">@pge</a>
                </li>
            }

            @if (pager.CurrentPage < pager.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="Items" asp-action="Index" asp-route-pg="@(pager.CurrentPage + 1)">Siguiente</a>
                </li>

                <li class="page-item">
                    <a class="page-link" asp-controller="Items" asp-action="Index" asp-route-pg="@(pager.TotalPages)">Final</a>
                </li>
            }

        </ul>
    }

</div>